name: Hammering

on:
  push:
    branches: [ '**' ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: windows-latest

    steps:
    - name: Install minimal stable
      uses: dtolnay/rust-toolchain@stable
    - uses: actions/checkout@v4
      with:
        fetch-depth: 100
    - name: Install Protoc
      uses: arduino/setup-protoc@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}

    # - name: Checkout 50c7a7e380de9f272d77edf5ef0238848b996416~0 and build
    #   run: git checkout 50c7a7e380de9f272d77edf5ef0238848b996416~0 && cargo test -p collection --lib --no-run
    - name: Run hammering
      shell: bash
      run: . ./tools/hammering.sh
